"""Run the rule automata over every recorded run and compare with the expected verdicts.

    python -m semalpha.verify                              # one line per run, then a summary
    python -m semalpha.verify t_stop_left wait_for_gap     # also show each automaton's state changes
    python -m semalpha.verify --docs                       # also write docs/automata.md
    python -m semalpha.verify --set gap_margin_s=3         # judge with a different label threshold

No simulation is run: this reads outputs/runs, labels them, and feeds the label
sequences to the automata in semalpha/rules.py.
"""
from __future__ import annotations

import sys
from dataclasses import dataclass
from typing import Dict, List, Tuple

import yaml

from semalpha import ROOT
from semalpha.automata import holds
from semalpha.expected import EXPECTED_VERDICT, Verdict
from semalpha.helpers import load_thresholds
from semalpha.label import Trace, label_run, run_file
from semalpha.predicates import PROPOSITIONS
from semalpha.record import Run
from semalpha.rules import AUTOMATA, IDLE_WHILE_FREE, RULES, reach_goal, where_it_waited
from semalpha.scenarios import SCENARIOS


@dataclass
class Judgement:
    states: Dict[str, List[str]]              # automaton name -> its state after each frame
    completed: bool                           # reach_goal ended in `done`
    progress: str                             # the state reach_goal ended in
    violations: List[Tuple[str, float]]       # (rule, time it was first broken)
    waited: str
    idle_while_free_s: float

    @property
    def verdict(self) -> Verdict:
        return Verdict(self.completed, tuple(rule for rule, _ in self.violations), self.waited)

    def summary(self) -> str:
        done = "completed" if self.completed else f"not completed (got as far as: {self.progress})"
        broken = ", ".join(f"{rule} at {t:.1f}s" for rule, t in self.violations) or "none"
        return f"{done} | rules broken: {broken} | halted: {self.waited} | idle while free: {self.idle_while_free_s:.1f}s"


def judge(trace: Trace) -> Judgement:
    states = {a.name: a.run(trace.labels) for a in AUTOMATA}
    violations = []
    for rule in RULES:
        for t, state in zip(trace.times, states[rule.name]):
            if state in rule.bad:
                violations.append((rule.name, t))
                break
    idle = sum(trace.run.dt for labels in trace.labels
               if any(holds(c, labels) for c in IDLE_WHILE_FREE))
    final = states[reach_goal.name][-1]
    return Judgement(states, final in reach_goal.good, final,
                     sorted(violations, key=lambda v: v[1]), states[where_it_waited.name][-1], idle)


def same(a: Verdict, b: Verdict) -> bool:
    return a.completed == b.completed and set(a.violations) == set(b.violations) and a.waited == b.waited


def describe(v: Verdict) -> str:
    return (f"{'completed' if v.completed else 'not completed'}; "
            f"rules broken: {', '.join(v.violations) or 'none'}; halted: {v.waited}")


def state_changes(trace: Trace, judgement: Judgement) -> str:
    lines = []
    for automaton in AUTOMATA:
        path, prev = [], automaton.initial
        for t, state in zip(trace.times, judgement.states[automaton.name]):
            if state != prev:
                path.append(f"{t:.1f}s {state}")
                prev = state
        lines.append(f"    {automaton.name:<26} {automaton.initial}" + "".join(f"  ->  {p}" for p in path))
    return "\n".join(lines)


def all_runs(args=(), thresholds=None):
    thresholds = thresholds or load_thresholds()
    for scenario in SCENARIOS.values():
        if args and scenario.name != args[0]:
            continue
        for variant in scenario.variants:
            if len(args) > 1 and variant.name != args[1]:
                continue
            for driver in ["sumo", *variant.scripts]:
                if len(args) > 2 and driver != args[2]:
                    continue
                key = (scenario.name, variant.name, driver)
                trace = label_run(Run.load(run_file(*key)), thresholds)
                yield key, trace, judge(trace)


def labels_used() -> List[str]:
    used = set().union(*(a.labels_used() for a in AUTOMATA))
    used |= {lit.lstrip("!") for c in IDLE_WHILE_FREE for lit in c.split()}
    return [p for p in PROPOSITIONS if p in used]


def write_docs(results, out=ROOT / "docs" / "automata.md") -> None:
    agree = sum(same(j.verdict, EXPECTED_VERDICT[k]) for k, _, j in results)
    used = labels_used()
    unused = [p for p in PROPOSITIONS if p not in used]
    md = [
        "# Rule automata",
        "",
        "Generated by `python -m semalpha.verify --docs` from `semalpha/rules.py`. Do not edit by hand.",
        "",
        "One set of small automata judges every scenario. Each reads the label sequence of a run,",
        "one frame at a time. None of them mentions a junction type.",
        "",
        "- **task**: `reach_goal` tracks progress; ending in `done` means the run succeeded.",
        "- **rule**: each watches one rule; once in `violated` it stays there.",
        "- **branch**: `where_it_waited` records which way the ego got through.",
        "",
        "Transitions are tried in the order listed; if none applies the automaton stays put.",
        "",
    ]
    for a in AUTOMATA:
        md += [f"## `{a.name}` ({a.kind})", "", a.rule, "", "```mermaid", a.to_mermaid(), "```", ""]
    md += [
        "## Verdicts on the recorded runs",
        "",
        f"{agree} of {len(results)} verdicts agree with the ones written down beforehand "
        "(`EXPECTED_VERDICT` in `semalpha/expected.py`).",
        "",
        "| Scenario | Variant | Driver | Completed | Rules broken | Halted | Idle while free | As expected |",
        "|---|---|---|:-:|---|---|--:|:-:|",
    ]
    for (scenario, variant, driver), _, j in results:
        broken = ", ".join(f"`{r}` at {t:.1f} s" for r, t in j.violations) or "none"
        ok = "yes" if same(j.verdict, EXPECTED_VERDICT[(scenario, variant, driver)]) else "**no**"
        md.append(f"| {scenario} | {variant} | {driver} | {'yes' if j.completed else 'no'} | {broken} "
                  f"| {j.waited} | {j.idle_while_free_s:.1f} s | {ok} |")
    broken_by = {rule.name: sum(any(r == rule.name for r, _ in j.violations) for _, _, j in results)
                 for rule in RULES}
    never = [name for name, n in broken_by.items() if n == 0]
    md += [
        "",
        "\"Idle while free\" is the time the ego stood still although the labels said nothing held",
        "it. It is measured directly from the labels, not by an automaton, because it counts time.",
        "",
        "## How far this result goes",
        "",
        "- Runs that break each rule: "
        + ", ".join(f"`{name}` {n}" for name, n in broken_by.items()) + ".",
        "- " + (f"No run breaks {', '.join(f'`{n}`' for n in never)}, so for those rules only the "
                "\"no false alarm\" side has been checked." if never else "Every rule is broken by at least one run."),
        "- The expected verdicts were written before the automata, but by someone who had already",
        "  seen the label sequences. Agreement shows that one rule set separates these runs",
        "  correctly on every junction type; it is not an independent test.",
        "- The runs are the same ones the labels were developed on.",
        "",
        "## Labels the rule set needs",
        "",
        f"Used ({len(used)}): " + ", ".join(f"`{p}`" for p in used) + ".",
        "",
        f"Not used by any automaton ({len(unused)}): " + (", ".join(f"`{p}`" for p in unused) or "none") + ".",
        "",
    ]
    out.write_text("\n".join(md), encoding="utf-8")
    print(f"wrote {out}")


def main(argv) -> int:
    thresholds = load_thresholds()
    args, overridden = [], False
    it = iter(argv)
    for a in it:
        if a == "--set":
            key, value = next(it).split("=")
            setattr(thresholds, key, yaml.safe_load(value))
            overridden = True
        elif not a.startswith("--"):
            args.append(a)
    results = list(all_runs(args, thresholds))
    agree = 0
    for key, trace, judgement in results:
        expected = EXPECTED_VERDICT[key]
        ok = same(judgement.verdict, expected)
        agree += ok
        print(f"{'ok  ' if ok else 'DIFF'} {key[0]:<16}{key[1]:<22}{key[2]:<20} {judgement.summary()}")
        if not ok:
            print(f"       expected: {describe(expected)}")
        if len(args) > 1:
            print(state_changes(trace, judgement))
    print(f"\n{agree} of {len(results)} verdicts as expected")
    if not args:
        used = labels_used()
        print(f"labels used by the automata ({len(used)}): {' '.join(used)}")
        print(f"labels not used: {' '.join(p for p in PROPOSITIONS if p not in used)}")
    if "--docs" in argv and not args and not overridden:
        write_docs(results)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
